# Generated by Django 4.2.1 on 2023-05-26 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('api_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ultrasonic_left_value', models.FloatField()),
                ('ultrasonic_right_value', models.FloatField()),
                ('gps_lat', models.FloatField()),
                ('gps_lng', models.FloatField()),
                ('gps_h', models.FloatField()),
                ('gps_m', models.FloatField()),
                ('gps_s', models.FloatField()),
                ('membership', models.CharField(choices=[('S', '0'), ('D', '1'), ('O', '2')], default='S', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Blind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.customer')),
            ],
        ),
    ]
