# Generated by Django 4.2.1 on 2023-05-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='membership',
            field=models.CharField(choices=[('S', '0'), ('D', '1'), ('O', '2')], default='S', max_length=1),
        ),
    ]
