# Generated by Django 4.2.1 on 2023-05-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='customer',
        ),
        migrations.AddField(
            model_name='device',
            name='blind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.blind'),
            preserve_default=False,
        ),
    ]
