# Generated by Django 4.2.1 on 2023-05-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_remove_device_customer_device_blind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='blind',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='device.blind'),
        ),
    ]
