# Generated by Django 4.2.1 on 2023-05-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_remove_device_user_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.customer'),
            preserve_default=False,
        ),
    ]
