# Generated by Django 4.2.1 on 2023-05-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_blind'),
    ]

    operations = [
        migrations.AddField(
            model_name='blind',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.customer'),
            preserve_default=False,
        ),
    ]
