# Generated by Django 4.1.7 on 2023-05-28 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('V1', '0002_alter_customer_address_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('api_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ultrasonic_left_value', models.CharField(max_length=255)),
                ('ultrasonic_right_value', models.CharField(max_length=255)),
                ('gps_lat', models.FloatField()),
                ('gps_lng', models.FloatField()),
                ('gps_h', models.FloatField()),
                ('gps_m', models.FloatField()),
                ('gps_s', models.FloatField()),
                ('status', models.CharField(choices=[('I', '0'), ('D', '1'), ('O', '2')], default='I', max_length=1)),
            ],
        ),
    ]
