# Generated by Django 4.1.7 on 2023-05-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('V1', '0003_blind_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='blind',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='V1.blind'),
            preserve_default=False,
        ),
    ]
