# Generated by Django 4.2.1 on 2023-06-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('V1', '0007_alter_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blind',
            name='user',
        ),
        migrations.AddField(
            model_name='blind',
            name='user',
            field=models.ManyToManyField(related_name='blinds', to='user.user'),
        ),
    ]
