# Generated by Django 4.2.1 on 2023-06-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('V1', '0008_remove_blind_user_blind_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blind',
            name='user',
        ),
        migrations.AddField(
            model_name='blind',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blinds', to='user.user'),
            preserve_default=False,
        ),
    ]
