# Generated by Django 4.2.1 on 2023-06-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V1', '0009_remove_blind_user_blind_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gps_h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='gps_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='gps_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='gps_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ultrasonic_left_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ultrasonic_right_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
