# Generated by Django 4.2.1 on 2023-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V1', '0010_alter_device_gps_h_alter_device_gps_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='c_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='c_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='r1_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='r2_radius',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
