# Generated by Django 4.2.1 on 2023-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V1', '0011_device_c_lat_device_c_lng_device_r1_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='c_lat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
